[project]
name = "flask-a11y"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "markdown2>=2.5.3",
    "python-frontmatter>=1.1.0",
    "python-lsp-server>=1.12.2",
]
